language: python
python:
  - "3.5.3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install --upgrade pip wheel
  - pip install --upgrade -r tests_requirements.txt
script:
  - flake8
  - py.test tests --cov=peony --timeout=30
cache: pip
after_success:
  - codecov
