language: python
sudo: false
python:
  - "3.5.0"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip wheel
  - pip install --upgrade -r tests_requirements.txt pytest-timeout
script:
  - flake8
  - py.test tests --cov=peony --timeout=300
cache: pip
after_success:
  - codecov
