language: python
python:
  - "3.5.0"
  - "3.5"
  - "3.6"
install:
  - pip install --upgrade pip wheel
  - pip install --upgrade -r tests_requirements.txt
script:
  - flake8
  - py.test tests --cov=peony
cache: pip
after_success:
  - codecov
